DROP TABLE geographic_units IF EXISTS;

CREATE TABLE geographic_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	anzsic06 VARCHAR(10),
    area VARCHAR(10),
    year_recorded VARCHAR(4),
    geo_count VARCHAR(10),
    ec_count VARCHAR(10)
);